import {
  Users,
  UserPlus,
  Mail,
  ChevronRight,
  ChevronLeft,
  Check,
  X,
  Upload,
  Download,
  Eye,
  Edit,
  Trash2,
  Search,
  Filter,
  CheckCircle,
  Menu,
  XCircle,
  AlertCircle,
} from 'lucide-react';

export const ICONS = {
  users: Users,
  userPlus: UserPlus,
  mail: Mail,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  check: Check,
  x: X,
  upload: Upload,
  download: Download,
  eye: Eye,
  edit: Edit,
  trash: Trash2,
  search: Search,
  filter: Filter,
  checkCircle: CheckCircle,
  menu: Menu,
  xCircle: XCircle,
  alertCircle: AlertCircle,
};
